name: event_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  get: ^4.6.5
  firebase_core: ^3.7.0  # Mise à jour vers la dernière version stable de firebase_core
  firebase_auth: ^5.3.2  # Vérifiez la compatibilité de firebase_auth avec la version de firebase_core
  firebase_auth_web: ^5.13.3
  google_sign_in: ^6.2.2
  shared_preferences: ^2.0.16
  cloud_firestore: ^5.4.5
  image_picker: ^1.1.2
  firebase: ^9.0.3
  hugeicons: ^0.0.7
  carousel_slider: ^5.0.0
  uuid: ^4.5.1
  firebase_storage: ^12.3.6
  url_launcher: ^6.3.1
  cached_network_image: ^3.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.2
  smooth_page_indicator: ^1.2.0+3
  flutter_lints: ^4.0.0

  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/
    - assets/fonts/

  fonts:
    - family: Sen
      fonts:
        - asset: assets/fonts/Sen-Regular.ttf
        - asset: assets/fonts/Sen-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sen-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sen-ExtraBold.ttf
          weight: 800